export const robots = [
  {
    id: 1,
    name: 'Steven Nelson',
    firstname: 'Steven',
    lastname: 'Nelson',
    username: 'slnelshm',
    position: 'Current IT Supervisor',
    speciality: 'IT Management & Remaining calm under pressure',
    nickname: 'The Bossman',
    hours: 'Mon - Fri (7am - 3pm)',
    phone: '(608) 846-8114',
    email: 'steven.nelson@walgreens.com'
  },
  {
    id: 2,
    name: 'Keith Sturm',
    firstname: 'Keith',
    lastname: 'Sturm',
    username: 'kasturm',
    position: 'DC IT Support Specialist',
    speciality: 'Printers, Truck Mounts, Thinclients & AS400',
    nickname: '?',
    hours: 'Mon - Fri (7am - 3pm)',
    phone: '(608) 846-8180',
    email: 'keith.sturm@walgreens.com'
  },
  {
    id: 3,
    name: 'Rick Dresen',
    firstname: 'Rick',
    lastname: 'Dresen',
    username: 'rwdres5j',
    position: 'DC IT Support Specialist',
    speciality: 'Networking, PC Troubleshooting & Video Games',
    nickname: 'The Dresenator',
    hours: 'Sun - Thu (3pm - 11pm)',
    phone: '(608) 846-8180',
    email: 'rick.dresen@walgreens.com'
  },
  {
    id: 4,
    name: 'Gina Graville',
    firstname: 'Gina',
    lastname: 'Gravill',
    username: 'ggravill',
    position: 'DC IT Support Specialist',
    speciality: 'AS400 & RF Guns/Gladiators',
    nickname: '?',
    hours: 'Mon, Tue, Wed, Thu (8am - 4pm), Fri (9pm - 5pm)',
    phone: '(608) 846-8180',
    email: 'gina.graville@walgreens.com'
  },
  {
    id: 5,
    name: 'John Gehring',
    firstname: 'John',
    lastname: 'Gehring',
    username: 'jgehring',
    position: 'DC IT Support Specialist',
    speciality: 'PC troubleshooting & Web Development',
    nickname: 'JohnBoy',
    hours: 'Mon - Fri (5pm - 1am)',
    phone: '(608) 846-8180',
    email: 'john.gehring@walgreens.com'
  },
  {
    id: 6,
    name: 'Lloyd Keen',
    firstname: 'Lloyd',
    lastname: 'Keen',
    username: 'lkeen',
    position: 'DC IT Support Specialist',
    speciality: 'AS400, OCE 7000 Printer Troubleshooting & Coffee',
    nickname: 'The Coffee Master',
    hours: 'Sun (10am - 6pm), Mon - Thu (3pm - 11pm)',
    phone: '(608) 846-8180',
    email: 'lloyd.keen@walgreens.com'
  },
  {
    id: 7,
    name: 'Jon Maly',
    firstname: 'Jon',
    lastname: 'Maly',
    username: 'jjmaly',
    position: 'DC IT Support Specialist',
    speciality: 'PC support, Bringing in wife\'s brownies & a quick wit',
    nickname: 'Mr. Maly',
    hours: 'Sun - Thu (11pm - 7am)',
    phone: '(608) 846-8180',
    email: 'jon.maly@walgreens.com'
  },
  /* {
    id: 8,
    name: 'Ryne Collies',
    firstname: 'Ryne',
    lastname: 'Collies',
    username: 'rrcollaj',
    position: 'Admin at another job',
    speciality: 'Forklift & saying Yo all the time',
    nickname: 'Mr. Yo',
    hours: 'Who knows',
    phone: '(608) 846-8180',
    email: 'ryne.collies@walgreens.com'
  },*/
  {
    id: 9,
    name: 'Cheryl Ogle',
    firstname: 'Cheryl',
    lastname: 'Ogle',
    username: 'coglehm',
    position: 'DC IT Support Specialist Backup',
    speciality: 'Filling in for absent support specialists',
    nickname: 'Mrs. Mysterious',
    hours: 'Whenever she is needed. Times vary.',
    phone: '(608) 846-8180',
    email: 'cheryl.ogle@walgreens.com'
  },
  /* {
    id: 10,
    name: 'Rick Walton',
    firstname: 'Rick',
    lastname: 'Walton',
    username: 'rawaltzr',
    position: 'Asset Protection Specialist',
    speciality: 'Databases & Asset Protection',
    nickname: 'Callsign Viper',
    hours: 'Mon - Fri (5pm - 1am)',
    phone: '(608) 846-8555',
    email: 'rick.walton@walgreens.com'
  } */
];
